name: Tests

on:
  push

jobs:
  test:
    name: Le Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: Unit 1 tests
      run: |
        python unit1-python-basics/problem_3.py