name: Tests

on:
  push

jobs:
  test:
    name: Le Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: Unit 1 tests
      run: |
        python MITx6.00.1x/unit1-python-basics/problem_3.py 
    - name: Unit 2 tests
      run: |
        python MITx6.00.1x/unit2-simple-programs/isin.py 
        python MITx6.00.1x/unit2-simple-programs/problem_1.py 
        python MITx6.00.1x/unit2-simple-programs/problem_2.py 
        python MITx6.00.1x/unit2-simple-programs/problem_3.py 
    - name: Unit 3 tests
      run: |
        python MITx6.00.1x/unit3-structured-types/_1_odd_tuples.py
        python MITx6.00.1x/unit3-structured-types/_2_how_many.py
        python MITx6.00.1x/unit3-structured-types/ps3_hangman_tests.py test